name: Deploy spec

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - run: npm install
      - run: npm run build
      - uses: elstudio/actions-js-build/commit@v3
        with:
          commitMessage: "fixup: [spec] `npm run build`"
