name: Polyfill

on: [push]

defaults:
  run:
    working-directory: ./packages/polyfill

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - name: Authenticate NPM
        uses: DimensionDev/github-token-action@latest
        with:
          registry: true
      - name: Install and Test
        run: npm cit
      - name: Lint
        run: npm run lint
      - name: Publish to GitHub Package (unstable)
        run: ./scripts/publish-to-github.sh
